# Generated by Django 2.2.6 on 2020-01-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
