# Generated by Django 2.2.6 on 2020-01-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200103_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Wish',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='task',
            new_name='wish',
        ),
    ]
